name: Update Gradle Wrapper

on:
  schedule:
    - cron: "10 8-13 * * MON-FRI"  # Every 10 mins from 8:30AM to 1:30PM weekdays

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          set-distribution-checksum: false
